# Generated by Django 2.1 on 2019-09-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190925_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_of_referals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payout_ampunt',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
