# Generated by Django 2.1 on 2019-09-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190926_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='payout_ampunt',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
