# Generated by Django 2.1 on 2019-09-27 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_account_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account_profile',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Userprofile', to_field='username'),
        ),
    ]
