# Generated by Django 2.1 on 2019-09-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal',
            field=models.CharField(max_length=100),
        ),
    ]
