# Generated by Django 2.1 on 2019-09-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190927_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account_profile',
            name='Qrcode',
        ),
        migrations.AddField(
            model_name='user_account_profile',
            name='upi',
            field=models.CharField(default='', max_length=100),
        ),
    ]
