# Generated by Django 2.1.5 on 2019-09-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=100)),
                ('Last_name', models.CharField(default='', max_length=100)),
                ('account_type', models.CharField(default='', max_length=100)),
                ('Address1', models.CharField(default='', max_length=100)),
                ('Address2', models.CharField(default='', max_length=100)),
                ('image', models.FileField(blank=True, upload_to='license')),
                ('refer', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
