# Generated by Django 2.1.5 on 2019-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_account_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('upi', models.CharField(default='', max_length=100)),
                ('bank_ifsc', models.CharField(default='', max_length=100)),
                ('Name_of_account_holder', models.CharField(default='', max_length=100)),
                ('uidai', models.CharField(default='', max_length=12)),
                ('pan', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_pic', models.FileField(default='', upload_to='media')),
                ('productinfo', models.IntegerField(default=0)),
                ('First_name', models.CharField(default='', max_length=100)),
                ('Last_name', models.CharField(default='', max_length=100)),
                ('account_type', models.CharField(default='', max_length=100)),
                ('Address1', models.CharField(default='', max_length=100)),
                ('Address2', models.CharField(default='', max_length=100)),
                ('txnid', models.CharField(default='', max_length=100)),
                ('discount', models.CharField(default='', max_length=100)),
                ('net_amount_debit', models.CharField(default='', max_length=100)),
                ('refer', models.CharField(max_length=100)),
                ('no_of_referals', models.IntegerField(default=0)),
                ('payout_ampunt', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('withdrawal', models.CharField(max_length=100)),
            ],
        ),
    ]
