# Generated by Django 2.1.5 on 2019-08-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190828_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='refer',
            field=models.CharField(max_length=100),
        ),
    ]
