# Generated by Django 2.1.5 on 2019-09-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190903_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Address1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Address2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
