# Generated by Django 2.1 on 2019-09-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190903_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Profile_pic',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
