# Generated by Django 2.1 on 2019-09-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190926_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_account_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qrcode', models.FileField(default='', upload_to='media')),
                ('bank_ifsc', models.CharField(default='', max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Userprofile')),
            ],
        ),
    ]
