# Generated by Django 2.1 on 2019-09-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190927_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account_profile',
            name='Name_of_account_holder',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_account_profile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
