# Generated by Django 2.1 on 2019-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190927_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('withdrawal', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
